### ISSUE TITLE
JSON Support

### ISSUE THREAD

**Issue by Jochyoua** [heretere/hch#2]
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**
I want JSON added as a configuration type.
JSON is more technical than YAML or TOML and would better hold information that wouldn't necessarily need to be edited by the end-user, but still a possibility. Plus, it's prettier.
**Describe alternatives you've considered**
I have not tried any alternatives yet.

**Comment by heretere** [comment]
Pog

**Comment by heretere** [comment]
JSON support has been added
