### ISSUE TITLE
Configuration file implementations

### ISSUE THREAD

**Issue by Jochyoua** [heretere/hch#3]
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**
I want the possibility of passing a pre-existing file through HCH and using the contents from that file instead of creating a constructor for using this API.
Allowing this will add the possibility of having multiple configuration files in their native format and editing them without creating a constructor. 
I will find this very useful.
**Describe alternatives you've considered**
I have not tried any alternatives yet.

**Comment by heretere** [comment]
Implementation finished just need to do some more testing.
